---
title: Fab.City
timezone: UTC+1
collections:
  cities:
    title: Cities
    output: true
  posts:
    title: Posts
    output: false
  uploads:
    title: Uploads
    output: false
sass:
  sass_dir: assets/css
plugins:
- jekyll-autoprefixer
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-compress-images
compress_images:
        images_path: "/assets/images/**/*.{gif,png,jpg,jpeg,svg}"
tagline: LOCALLY PRODUCED, GLOBALLY CONNECTED
email: your.email@gmail.com
description:
author: Fab City
coder: j0r15
url: https://fabcity.github.io/
baseurl:
google_analytics: UA-111111111-1
markdown: kramdown
social:
- title: twitter
  url: https://twitter.com/fabcityglobal
- title: facebook
  url: https://www.facebook.com/fabcityglobal/
