url: 
baseurl: 

# Site settings
title: Fab City Global Initiative
tagline: "Locally productive, globally connected cities"
email: info@fablabbcn.org
description: ""


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/fabcityglobal
  - title: facebook
    url: https://www.facebook.com/fabcityglobal/

# Postal address (add as many lines as necessary)
address:
  - line: "Calle Pujades 102"
  - line: "Poble Nou, Barcelona 08005 Spain"

# Build settings
markdown: kramdown
permalink: pretty